# Generated by Django 3.0.2 on 2020-03-31 14:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eicapp', '0002_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='argument',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='screedId',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
